### 200 + json

GET http://127.0.0.1:5000/groups

### 200 + json

GET http://127.0.0.1:5000/groups/21

### 200 + null

GET http://127.0.0.1:5000/groups/211

### 200 + json

GET http://127.0.0.1:5000/groups/21/tasks

### 200 --- just testing of @app.get("/groups2")

GET http://127.0.0.1:5000/groups2

### 200 --- just testing of @app.get("/groups2/<int:g_id>/tasks")

GET http://127.0.0.1:5000/groups2/21/tasks
