"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""

from .data_store import *


class GroupLi(Base):
    __abstract__ = True

    g_id = Column('g_id', autoincrement=True)
    g_name = Column('g_name')
    g_comments = Column('g_comments')
    tasks_count = Column('tasks_count')

    SQL = """select g.*,  
                (select count(*) from tasks where g_id=g.g_id) as tasks_count 
                from groups g 
                order by g.g_id"""
